#!/usr/bin/env python3
"""
OCR the Star Wars Rebellion (1998) manual PDF with Mistral OCR 4.1.

Produces:
  1. A Markdown transcription with YAML front matter and page anchors
     (written beside the PDF).
  2. A raw .ocr.json diagnostics file (written to .artifacts/manual-ocr/).

Figure annotations are NOT generated by this script.  They are added
in a separate caption-driven step (see README.md) because the bbox
annotation API hallucinates descriptions and figure numbers on scanned
pages with dark backgrounds and mixed imagery.

Usage:
  export MISTRAL_API_KEY=...  # your key
  uv run --with pymupdf --with 'mistralai>=2' python3 scripts/manual-ocr/ocr_manual.py

Chunks are processed sequentially to avoid 429 rate limits.
"""

import argparse
import base64
import datetime
import hashlib
import json
import logging
import os
import re
import shutil
import sys
import tempfile
import time
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

try:
    from mistralai.client import Mistral
except ImportError:
    logger.error("mistralai >= 2 required. Run with: uv run --with 'mistralai>=2' ...")
    sys.exit(1)

try:
    import fitz  # PyMuPDF
except ImportError:
    logger.error("PyMuPDF required. Run with: uv run --with pymupdf ...")
    sys.exit(1)

MODEL = "mistral-ocr-4-1"
LOW_CONFIDENCE = 0.6
CHUNK_SIZE = 20
LOOP = re.compile(r"(.{1,30}?)(?:\s*\1){11,}")
BENIGN_LOOP = re.compile(r"^[\s.·•\-–—_|=*~#:]+$")
CJK = re.compile(r"[぀-ヿ㐀-鿿가-힯]")

# bbox_annotation_format was removed.  Mistral OCR's image_annotation
# output hallucinated descriptions and recycled the schema's example
# figure number on nearly every page.  Figure annotations are now added
# in a separate caption-driven step (see README.md).

# Page offset table: (first_pdf_page, last_pdf_page, offset)
# printed_page = pdf_page + offset
# Front matter and back cover have no printed page numbers.
PAGE_OFFSETS = [
    # (pdf_start, pdf_end, offset, label)
    (1, 8, None, "front_matter"),        # Cover, title, intros, TOC
    (9, 17, 0, "chapter_1"),             # Chapter 1: Overview/Installation
    (18, 58, 1, "chapter_2"),            # Chapter 2: Tutorials
    (59, 135, 2, "chapter_3"),           # Chapter 3: Gameplay
    (136, 150, 3, "chapter_4"),          # Chapter 4: Tactical
    (151, 166, 4, "chapter_5_and_back"), # Chapter 5 + Credits/Glossary
    (167, 167, None, "back_cover"),      # Back cover
]


def pdf_to_printed(pdf_page: int) -> int | None:
    """Convert a 1-based PDF page number to a printed page number, or None."""
    for start, end, offset, _label in PAGE_OFFSETS:
        if start <= pdf_page <= end:
            if offset is None:
                return None
            return pdf_page + offset
    return None


def offset_table_yaml() -> str:
    """Return the offset table as YAML for the front matter."""
    lines = []
    for start, end, offset, label in PAGE_OFFSETS:
        if offset is None:
            lines.append(f"  - pdf_pages: \"{start}-{end}\"")
            lines.append(f"    printed: null")
            lines.append(f"    label: \"{label}\"")
        else:
            printed_start = start + offset
            printed_end = end + offset
            lines.append(f"  - pdf_pages: \"{start}-{end}\"")
            lines.append(f"    printed: \"{printed_start}-{printed_end}\"")
            lines.append(f"    offset: {offset}")
            lines.append(f"    label: \"{label}\"")
    return "\n".join(lines)


def text_checks(markdown: str) -> dict:
    """Signatures of failed OCR in the page text."""
    loops = sum(
        len(m.group(0))
        for m in LOOP.finditer(markdown)
        if not BENIGN_LOOP.match(m.group(1))
    )
    return {
        "loop_chars": loops,
        "layout_json": '"box_2d"' in markdown or '[{"' in markdown,
        "cjk_chars": len(CJK.findall(markdown)),
    }


def page_diagnostics(page, pdf_page: int, model: str) -> dict:
    """Compact per-page diagnostics record."""
    conf = getattr(page, "confidence_scores", None)
    words = list(getattr(conf, "word_confidence_scores", None) or [])
    dims = page.dimensions
    blocks = []
    for b in getattr(page, "blocks", None) or []:
        content = (b.content or "").strip()
        blocks.append({
            "type": b.type,
            "box": [b.top_left_x, b.top_left_y, b.bottom_right_x, b.bottom_right_y],
            "chars": len(content),
            "digest": hashlib.sha1(content.encode("utf-8")).hexdigest()[:12],
            "head": content[:40],
        })
    return {
        "pdf_page": pdf_page,
        "model": model,
        "width": dims.width,
        "height": dims.height,
        "dpi": dims.dpi,
        "avg_confidence": getattr(conf, "average_page_confidence_score", None),
        "min_confidence": getattr(conf, "minimum_page_confidence_score", None),
        "words": len(words),
        "low_words": [
            [w.text.strip(), round(w.confidence, 3)]
            for w in words
            if w.confidence < LOW_CONFIDENCE
        ],
        **text_checks(page.markdown or ""),
        "blocks": blocks,
    }


def ocr_chunk(chunk_path: str, api_key: str) -> tuple:
    """OCR a single chunk PDF, returning (pages_list, diagnostics_list)."""
    client = Mistral(api_key=api_key)

    with open(chunk_path, "rb") as f:
        pdf_base64 = base64.standard_b64encode(f.read()).decode("utf-8")

    data_url = f"data:application/pdf;base64,{pdf_base64}"

    response = client.ocr.process(
        model=MODEL,
        document={
            "type": "document_url",
            "document_url": data_url,
        },
        include_image_base64=False,
        include_blocks=True,
        confidence_scores_granularity="word",
    )

    pages = []
    diagnostics = []

    for page in response.pages:
        local_idx = page.index  # 0-based within this chunk
        pages.append({
            "index": local_idx,
            "markdown": page.markdown or "",
        })
        diagnostics.append(page)

    return pages, diagnostics


def run_ocr(pdf_path: Path, api_key: str) -> tuple:
    """OCR the full PDF in chunks. Returns (all_pages, all_diagnostics)."""
    doc = fitz.open(str(pdf_path))
    total_pages = len(doc)
    logger.info(f"PDF has {total_pages} pages, processing in chunks of {CHUNK_SIZE}...")

    all_pages = []  # list of (pdf_page_1based, markdown)
    all_diagnostics = []

    temp_dir = Path(tempfile.mkdtemp(prefix="manual_ocr_chunks_"))
    total_chunks = (total_pages + CHUNK_SIZE - 1) // CHUNK_SIZE

    for chunk_num, start in enumerate(range(0, total_pages, CHUNK_SIZE), 1):
        end = min(start + CHUNK_SIZE, total_pages)
        chunk_path = temp_dir / f"chunk_{start}_{end}.pdf"

        logger.info(f"Chunk {chunk_num}/{total_chunks}: pages {start + 1}-{end}")
        chunk_doc = fitz.open()
        chunk_doc.insert_pdf(doc, from_page=start, to_page=end - 1)
        chunk_doc.save(str(chunk_path))
        chunk_doc.close()

        try:
            pages, diags = ocr_chunk(str(chunk_path), api_key)
            for p in pages:
                pdf_page = start + p["index"] + 1  # 1-based
                all_pages.append((pdf_page, p["markdown"]))
            for d in diags:
                all_diagnostics.append(
                    page_diagnostics(d, pdf_page=start + d.index + 1, model=MODEL)
                )
            logger.info(f"Chunk {chunk_num}/{total_chunks}: OK ({len(pages)} pages)")
        except Exception as e:
            logger.error(f"Chunk {chunk_num}/{total_chunks} FAILED: {e}")
            for i in range(start, end):
                all_pages.append((i + 1, f"<!-- OCR FAILED for PDF page {i + 1}: {e} -->"))

        try:
            chunk_path.unlink()
        except Exception:
            pass

        # Brief pause between chunks to avoid rate limits
        if chunk_num < total_chunks:
            time.sleep(2)

    doc.close()
    shutil.rmtree(temp_dir, ignore_errors=True)

    return all_pages, all_diagnostics


def assemble_markdown(
    all_pages: list,
    pdf_path: Path,
    sha256: str,
    total_pages: int,
) -> str:
    """Assemble the final Markdown with YAML front matter and page anchors.

    Figure annotations are NOT included here -- they are added in a
    separate caption-driven step after the OCR run (see README.md).
    """
    lines = []

    # YAML front matter
    lines.append("---")
    lines.append('title: "Star Wars: Rebellion -- Game Manual"')
    # Source path relative to repo root
    try:
        repo_root = Path(__file__).resolve().parents[2]
        rel = pdf_path.relative_to(repo_root)
    except ValueError:
        rel = pdf_path.name
    lines.append(f"source: {rel}")
    lines.append(f"sha256: {sha256}")
    lines.append(f"page_count: {total_pages}")
    lines.append("page_offset_table:")
    lines.append(offset_table_yaml())
    lines.append(f"ocr_model: {MODEL}")
    lines.append("ocr_date: 2026-10-06")
    lines.append("generator: scripts/manual-ocr/ocr_manual.py")
    lines.append("note: >-")
    lines.append("  OCR transcription of a scanned PDF with no text layer,")
    lines.append("  produced by Mistral OCR 4.1.  Figure annotations are")
    lines.append("  added in a separate caption-driven step; the PDF remains")
    lines.append("  the authority for images.")
    lines.append("---")
    lines.append("")

    for pdf_page, markdown in all_pages:
        printed = pdf_to_printed(pdf_page)
        if printed is not None:
            lines.append(f"<!-- pdf-page: {pdf_page} | printed: {printed} -->")
            lines.append(f"## p. {printed}")
        else:
            lines.append(f"<!-- pdf-page: {pdf_page} | printed: n/a -->")
            lines.append(f"## [PDF page {pdf_page}]")
        lines.append("")

        # Insert the OCR markdown (text only, no image links)
        # Strip any ![img-...] lines from the raw OCR output
        cleaned = "\n".join(
            ln for ln in markdown.strip().splitlines()
            if not ln.startswith("![img-")
        )
        lines.append(cleaned)
        lines.append("")

    return "\n".join(lines)


def get_api_key() -> str:
    """Get the Mistral API key from the environment."""
    key = os.environ.get("MISTRAL_API_KEY")
    if not key:
        logger.error("No API key: export MISTRAL_API_KEY first.")
        sys.exit(1)
    return key


def sha256_file(path: Path) -> str:
    """Compute SHA-256 of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    parser = argparse.ArgumentParser(description="OCR the SW Rebellion manual with Mistral OCR 4.1")
    parser.add_argument(
        "--pdf",
        default="docs/reference/campaign-history/archive/star-wars-rebellion-manual.pdf",
        help="Path to the PDF (default: the manual in the archive)",
    )
    parser.add_argument(
        "--output",
        default="docs/reference/campaign-history/archive/star-wars-rebellion-manual.md",
        help="Output Markdown path",
    )
    parser.add_argument(
        "--diagnostics-dir",
        default=".artifacts/manual-ocr",
        help="Directory for raw .ocr.json diagnostics",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    pdf_path = (repo_root / args.pdf).resolve()
    output_path = (repo_root / args.output).resolve()
    diag_dir = (repo_root / args.diagnostics_dir).resolve()

    if not pdf_path.exists():
        logger.error(f"PDF not found: {pdf_path}")
        sys.exit(1)

    diag_dir.mkdir(parents=True, exist_ok=True)
    api_key = get_api_key()

    logger.info("=" * 60)
    logger.info("Star Wars Rebellion Manual OCR")
    logger.info("=" * 60)
    logger.info(f"PDF:    {pdf_path}")
    logger.info(f"Output: {output_path}")
    logger.info(f"Model:  {MODEL}")

    sha = sha256_file(pdf_path)
    logger.info(f"SHA256: {sha}")

    doc = fitz.open(str(pdf_path))
    total_pages = len(doc)
    doc.close()
    logger.info(f"Pages:  {total_pages}")
    logger.info("-" * 60)

    start_time = time.time()
    all_pages, all_diagnostics = run_ocr(pdf_path, api_key)

    # Write diagnostics JSON
    diag_path = diag_dir / "star-wars-rebellion-manual.ocr.json"
    diag_path.write_text(
        json.dumps(
            {
                "pdf": pdf_path.name,
                "requested_model": MODEL,
                "low_confidence_below": LOW_CONFIDENCE,
                "created": datetime.datetime.now(datetime.timezone.utc).strftime(
                    "%Y-%m-%dT%H:%M:%SZ"
                ),
                "box_units": "pixels of the page image at (width, height)",
                "pages": all_diagnostics,
            },
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    logger.info(f"Diagnostics: {diag_path}")

    # Assemble and write Markdown
    markdown = assemble_markdown(all_pages, pdf_path, sha, total_pages)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")

    elapsed = time.time() - start_time
    size_kb = output_path.stat().st_size / 1024
    logger.info("-" * 60)
    logger.info(f"DONE in {elapsed:.0f}s")
    logger.info(f"Output: {output_path} ({size_kb:.1f} KB)")
    logger.info(f"Diagnostics: {diag_path}")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
